# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='date_meeting',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date meeting'),
            preserve_default=False,
        ),
    ]
