# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20170901_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='date_meeting',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='party',
            name='pub_date',
            field=models.CharField(max_length=200),
        ),
    ]
