# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20170905_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
