# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 19:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20170906_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='pub_date',
        ),
    ]
