# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_remove_party_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='party_beer_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
