# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_party_party_beer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_beer_image',
            field=models.ImageField(default=0, height_field='height_field', upload_to='', width_field='width_field'),
            preserve_default=False,
        ),
    ]
