# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:01
from __future__ import unicode_literals

import community.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_party_party_beer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_beer_image',
            field=stdimage.models.StdImageField(default=1, upload_to=community.models.upload_location),
            preserve_default=False,
        ),
    ]
