# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 01:43
from __future__ import unicode_literals

import beereview.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('nation', models.CharField(max_length=30)),
                ('abv', models.DecimalField(decimal_places=2, max_digits=4)),
                ('description', models.TextField(default='BEER Description HERE')),
                ('overall_score', models.DecimalField(decimal_places=9, default=0, max_digits=10)),
                ('beer_image', stdimage.models.StdImageField(blank=True, upload_to=beereview.models.beer_img_upload_location)),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('reviews_count', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment_deleted', models.BooleanField(default=False)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_reviews', to='beereview.Beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BeerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production_Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='beertype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beertype_beers', to='beereview.BeerType'),
        ),
        migrations.AddField(
            model_name='beer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_beers', to='beereview.Production_Company'),
        ),
    ]
