# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beereview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='beer',
            name='beertype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beertype_beers', to='beereview.BeerType'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_beers', to='beereview.Production_Company'),
        ),
    ]
