# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beereview', '0002_auto_20170823_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('overall_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beer',
            name='nation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='beertype',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='beerreview',
            name='beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_reviews', to='beereview.Beer'),
        ),
    ]
