# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 02:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beereview', '0003_auto_20170824_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
