# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beereview', '0004_auto_20170901_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='overall_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
