# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 09:20
from __future__ import unicode_literals

import beereview.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('beereview', '0006_auto_20170908_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='beerreview',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='beertype',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='production_company',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='calorie',
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_image',
            field=stdimage.models.StdImageField(blank=True, upload_to=beereview.models.beer_img_upload_location),
        ),
        migrations.AddField(
            model_name='beer',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='beerreview',
            name='comment_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='beer',
            name='overall_score',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='overall_score',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
