# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 15:48
from __future__ import unicode_literals

import beereview.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('beereview', '0006_auto_20170908_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='image_avater',
            field=stdimage.models.StdImageField(default=1, upload_to=beereview.models.upload_location),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beer',
            name='image_recommend',
            field=stdimage.models.StdImageField(default=1, upload_to=beereview.models.upload_location),
            preserve_default=False,
        ),
    ]
