# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beereview', '0007_auto_20170909_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='total_sum',
            field=models.DecimalField(decimal_places=99, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beer',
            name='overall_score',
            field=models.DecimalField(decimal_places=9, max_digits=10),
        ),
    ]
