# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170917_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfiles',
        ),
    ]
